version: "3.8"
services:
  node:
    image: node:18-alpine
    container_name: node
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: yarn run build:dev
    volumes:
      - ./:/app
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: habitstacker
    working_dir: /opt/app
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /opt/app
    ports:
      - "8000:8000"
    entrypoint: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - node
