# Generated by Django 5.0 on 2024-01-23 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_alter_habitlog_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habitlog",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_habit", "View Habit Objects"),),
            },
        ),
    ]
