# Generated by Django 5.0 on 2024-01-23 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0004_alter_habitlog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habitlog",
            options={},
        ),
    ]
