# Generated by Django 5.0 on 2024-01-23 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0006_alter_habitlog_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitlog",
            name="completed",
        ),
    ]
