dbs:
  # Replicate production database in Azure Storage Account
  - path: /app/database/prod.sqlite3
    replicas:
      - type: abs
        account-name: stcoderustle
        bucket: databases
        path: prod.sqlite3
