dbs:
  # Replicate production database in Azure Storage Account
  - path: /opt/habitstacker/database/db.sqlite3
    replicas:
      - type: abs
        account-name: coderustle
        bucket: database
        path: habitstacker/db.sqlite3
