dbs:
  # Replicate production database in Azure Storage Account
  - path: /app/database/prod.sqlite3
    replicas:
      - type: abs
        account-name: coderustle
        bucket: database
        path: habitstacker/prod.sqlite3
