name: Build template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      requirements:
        default: 'dev'
        required: false
        type: string
      image_name:
        default: 'habitstacker'
        required: false
        type: string
      target:
        default: 'development'
        required: false
        type: string
      push:
        default: true
        required: false
        type: boolean
      tag:
        default: 'dev'
        required: false
        type: string
    secrets:
      SECRET_KEY:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ${{ inputs.target }}
          push: ${{ inputs.push }}
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DJANGO_SETTINGS_MODULE=${{ vars.DJANGO_SETTINGS_MODULE }}
            PYTHON_REQUIREMENTS_FILE=${{ inputs.requirements }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ inputs.tag }}
          cache-to: type=inline
